### ISSUE TITLE
Sprint 1 [BETA]:

### ISSUE THREAD

**Issue by jonleung** [hackedu/pm#1]
Pre Launch
- [ ] Make sure that each task and project is 
  - [ ] actionable
  - [ ] under 6 words
- [ ] Create issues for each of the root bullet points
- [ ] Checkin with Ben and Gemma on commitments
### Primary Objective Categories
- Processes
- Create the best possible SF clubs
- Scaffold Club in a Box
- Visit schools in the Bay Area
- Create timeline
- Get More Dinocoins
## Sprint Participants

@zachlatta @jonleung @MaxWofford @gemmabusoni @benzweig
## Sprint Deliverables
- Culture
- [ ] Onboarding 
  - [ ] **Hypothesize systems for team engagement** (@jonleung @zachlatta) #d4
  - [ ] **Choose a tool like OKR & Scrum**  (@jonleung @zachlatta) #d4
  - [ ] **Create readme for initial set of systems** (@jonleung) #d4
    - [ ] Github Issues
    - [ ] IRC channels / IRC Cloud
    - [ ] Standups
    - [ ] FastMail Calendars
    - [ ] One-on-Ones
  - [ ] **Create a questions about unknowns** (@jonleung) #d5
  - [ ] **Create a list of mentors** (@jonleung) #d5
  - [ ] **Contact mentors** (@jonleung) #d5
  - [ ] **Onboard** (@jonleung) #d5
    - [ ] @zachlatta 
    - [ ] @MaxWofford 
    - [ ] @benzweig 
    - [ ] @gemmabusoni 
    - [x] @chaoyi
    - [ ] @sortoamy
- [ ] Prepare 2 best club meetings possible
  - [ ] **Start more clubs #d4**
    - [ ] How many more?
  - [ ] **Create experience**
    - [ ] Find best experience design from personal, online, club leaders, friends
  - [ ] **Measure & studey experience**
    - [ ] What's working well / not?
    - [ ] Where are the pain points?
    - [ ] Create measurable metrics.
  - [ ] **Email club leaders for their help**
    - [ ] send progress email update
    - [ ] asking club leaders if they have these pain points and how they may solve them
    - [ ] asking how do you measure if a club could improve
  - [ ] **Build an outline of the contnets of the CIAB into CIAB**
    - [ ] curricula
    - [ ] team building
    - [ ] etc.
- [ ] Visit schools in the Bay Area
  - [ ] **compile a list of every high school club we know**
    - [ ] what meeting days, school, address, number of club members, faculty contact information
- [ ] Create a timeline (@jonleung @zachlatta) #d5
  - [ ] **Apr - May**
  - [ ] **Jun - Jul**
  - [ ] **Aug - Sep**
  - [ ] **Oct - Nov**
- [ ] Get dinocoins @jonleung @zachlatta
  - [ ] **Respond to existing emails** (@jonl) #d4 
  - [ ] **Create a rank ordered list of 10 contacts to reach out to** (@jonl) #d5
- [ ] Plan the next sprint @jonleung @zachlatta (@jonl @zachlatta) #d7
  - [ ] **Create next sprint and publish it on Github issues**

**Comment by zachlatta** [comment]
Can we close this?
