### ISSUE TITLE
hackEDU applicant workflow should forward to pipedrive automatically

### ISSUE THREAD

**Issue by maxwofford** [hackedu/pm#11]

**Comment by maxwofford** [comment]
I don't find pipedrive very useful for managing applicant onboarding. Maybe if applicants were automatically input into pipedrive I would use it more.
This might actually be better in https://github.com/hackedu/hackedu. Thoughts @zachlatta?

**Comment by zachlatta** [comment]
We should probably create a separate repo for issues like these—the `pm` repo should only have sprints as issues.

Have you been BCCing Pipedrive on all applicant emails and processing those emails into their respective deals on Pipedrive?

**Comment by zachlatta** [comment]
Closing for now. Can you create this issue in https://github.com/hackedu/docs (which will be renamed to `meta`)?

**Comment by maxwofford** [comment]
Moved to https://github.com/hackedu/docs/issues/34
