### ISSUE TITLE
Sprint Discussion Time

### ISSUE THREAD

**Issue by jonleung** [hackedu/pm#13]
Please indicate on this [when2meet](http://www.when2meet.com/?2978366-1fuL6) what times you can consistently commit to every week for 1 hour to be free.

Please try to be conservative with which times really work best for you so that we can optimize for you to be at every meeting.

**Comment by gemmabusoni** [comment]
8:30 on Thursday.

**Comment by zachlatta** [comment]
Did we get this figured out? Can it be closed?

**Comment by jonleung** [comment]
@zachlatta no, still working on it

**Comment by jonleung** [comment]
So based on the [when2meet](http://www.when2meet.com/?2978366-1fuL6) and also the fact that we want these at the beginning of the week, it seems that the optimal time to do it is Mondays at 6:00pm PT and 9:00 ET Mondays.

**Is there any preference for moving it the time slightly before or afterwards?**

**Comment by zachlatta** [comment]
Either is good!

**Comment by jonleung** [comment]
Based on [this posting in hackEDU Leaders](https://www.facebook.com/groups/1501083703514499/permalink/1571124109843791/), the time for sprint discusses is slated for Mondays at 5:30pm PT and 8:30pm ET.

**Comment by zachlatta** [comment]
Can you submit this change in a PR? Ideally in one separate from #12 so
it can be merged quickly.
