### ISSUE TITLE
Where are we keeping track of incoming donations / sponsorships?

### ISSUE THREAD

**Issue by jonleung** [hackedu/pm#2]
As a reminder, we need to have these to Tyson each month.

**Comment by jonleung** [comment]
We also need to include private information like the fact that one of our donors is interested in visiting a club in Chicago and why. I propose we just keep a google spreadsheet or a libre office sheet in DB for this. Thoughts?

**Comment by zachlatta** [comment]
Just created a LibreOffice spreadsheet with our revenue over at zachlatta/fundraising@db8b4d077a5e2434622404cdc9e086b7704332b6.
