### ISSUE TITLE
Get Dashlane Pro

### ISSUE THREAD

**Issue by jonleung** [hackedu/pm#3]
How's this going?

**Comment by maxwofford** [comment]
Dashlane will provide us with free accounts, but we must prove that we have nonprofit status through a discrete service. Info on this can be found in the general hackedu mailing list (search for Dashlane).

**Comment by zachlatta** [comment]
Should we move this to https://github.com/zachlatta/fundraising?

**Comment by zachlatta** [comment]
Can you link to the Dashlane thread in
https://groups.google.com/forum/#!forum/hackedu-emails? I briefly
searched, but didn't see anything (I was probably being dumb and
missed it).

**Comment by maxwofford** [comment]
@jonleung can you take lead on this?

@zachlatta I forwarded to @jonleung for the time being.

**Comment by zachlatta** [comment]
Happy to take lead on this as well. I'm already sending emails all day, haha.

**Comment by zachlatta** [comment]
Closing for now. Can you reopen in https://github.com/zachlatta/fundraising?

**Comment by maxwofford** [comment]
Moved: https://github.com/zachlatta/fundraising/issues/5
